version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: docker.nginx
    image: my-nginx
    container_name: my-nginx-container
    ports:
      - "8080:8080"
    volumes:
      - wwwroot:/wwwroot
  webpack:
    build:
      context: .
      dockerfile: docker.webpack
    image: my-webpack
    container_name: my-webpack-container
    ports:
      - "35729:35729" // for live reload
    volumes:
      - .:/app
      - /app/node_modules
      - wwwroot:/wwwroot
volumes:
  wwwroot:
    driver: local